# Generated by Django 5.0.3 on 2024-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_airtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('AIRTEL', 'AIRTEL'), ('GLO', 'GLO'), ('9MOBILE', '9MOBILE')], max_length=100),
        ),
    ]
