# Generated by Django 5.0.3 on 2024-05-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_airtime_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
