# Generated by Django 5.0.3 on 2024-05-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_bvn_user_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bvn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
