# Generated by Django 5.0.3 on 2024-05-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_user_bvn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tx_ref',
            new_name='order_ref',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
