# Generated by Django 5.0.3 on 2024-05-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_tx_ref_user_order_ref_user_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='order_ref',
            new_name='account_reference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bvn',
        ),
    ]
