# Generated by Django 5.0.3 on 2024-05-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_order_ref_user_account_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
