# Generated by Django 5.0.3 on 2024-05-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
