# Generated by Django 5.0.3 on 2024-05-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flutter_secret_key',
            field=models.CharField(default='Bearer FLWSECK-fab12578d0fa352253f89fd6a7b7b713-18f55ce05d4vt-X', max_length=200),
        ),
    ]
