# Generated by Django 5.0.2 on 2024-05-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_user_flutter_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='flutter_secret_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pics',
        ),
    ]
